%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\wsl.localhost\Ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab2\matlab\plot_data.csv
%
% Auto-generated by MATLAB on 11-Jun-2026 18:15:32

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x__time", "x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_1_velocity", "x_joint_states_joint_2_position", "x_joint_states_joint_2_velocity"];
opts.SelectedVariableNames = ["x__time", "x_joint_states_joint_1_velocity", "x_joint_states_joint_2_velocity"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "double", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_2_position"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_2_position"], "EmptyFieldRule", "auto");

% Import the data
joint_velocity = readtable("\\wsl.localhost\Ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab2\matlab\plot_data.csv", opts);

%% Convert to output type
joint_velocity = table2array(joint_velocity);


%% Clear temporary variables
clear opts