%% Import data from text file
% Auto-generated by MATLAB on 14-Jun-2026 09:46:09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 18);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x__time", "x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_x", "x_current_EE_pose_pose_position_y", "x_current_EE_pose_pose_position_z", "x_external_wrenches_force_x", "x_external_wrenches_force_y", "x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z"];
opts.SelectedVariableNames = ["x__time", "x_current_EE_pose_pose_position_x", "x_current_EE_pose_pose_position_y", "x_external_wrenches_force_x", "x_external_wrenches_force_y"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "string", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_z", "x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_z", "x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z"], "EmptyFieldRule", "auto");

% Import the data
data_B = readtable("\\wsl.localhost\ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab4\matlab\data_x.csv", opts);

%% Asignar a variables y rellenar NaN
tiempo = data_B.x__time;
pos_x = data_B.x_current_EE_pose_pose_position_x;
pos_y = data_B.x_current_EE_pose_pose_position_y;
fuerza_x = data_B.x_external_wrenches_force_x;
fuerza_y = data_B.x_external_wrenches_force_y;

pos_x = fillmissing(pos_x, 'linear');
pos_y = fillmissing(pos_y, 'linear');
fuerza_x = fillmissing(fuerza_x, 'linear');
fuerza_y = fillmissing(fuerza_y, 'linear');

% Normalizar tiempo
tiempo = tiempo - tiempo(1);

%% Clear temporary variables
clear opts data_B