%% Import data from text file
% Auto-generated by MATLAB on 14-Jun-2026 11:30:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x__time", "x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_x", "x_current_EE_pose_pose_position_y", "x_current_EE_pose_pose_position_z", "x_equilibrium_pose_header_header_stamp", "x_equilibrium_pose_pose_orientation_pitch", "x_equilibrium_pose_pose_orientation_roll", "x_equilibrium_pose_pose_orientation_w", "x_equilibrium_pose_pose_orientation_x", "x_equilibrium_pose_pose_orientation_y", "x_equilibrium_pose_pose_orientation_yaw", "x_equilibrium_pose_pose_orientation_z", "x_equilibrium_pose_pose_position_x", "x_equilibrium_pose_pose_position_y", "x_equilibrium_pose_pose_position_z"];
opts.SelectedVariableNames = ["x__time", "x_current_EE_pose_pose_position_x", "x_current_EE_pose_pose_position_y", "x_equilibrium_pose_pose_position_x", "x_equilibrium_pose_pose_position_y"];
opts.VariableTypes = ["double", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_z", "x_equilibrium_pose_header_header_stamp", "x_equilibrium_pose_pose_orientation_pitch", "x_equilibrium_pose_pose_orientation_roll", "x_equilibrium_pose_pose_orientation_w", "x_equilibrium_pose_pose_orientation_x", "x_equilibrium_pose_pose_orientation_y", "x_equilibrium_pose_pose_orientation_yaw", "x_equilibrium_pose_pose_orientation_z", "x_equilibrium_pose_pose_position_z"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["x_current_EE_pose_header_header_stamp", "x_current_EE_pose_pose_orientation_pitch", "x_current_EE_pose_pose_orientation_roll", "x_current_EE_pose_pose_orientation_w", "x_current_EE_pose_pose_orientation_x", "x_current_EE_pose_pose_orientation_y", "x_current_EE_pose_pose_orientation_yaw", "x_current_EE_pose_pose_orientation_z", "x_current_EE_pose_pose_position_z", "x_equilibrium_pose_header_header_stamp", "x_equilibrium_pose_pose_orientation_pitch", "x_equilibrium_pose_pose_orientation_roll", "x_equilibrium_pose_pose_orientation_w", "x_equilibrium_pose_pose_orientation_x", "x_equilibrium_pose_pose_orientation_y", "x_equilibrium_pose_pose_orientation_yaw", "x_equilibrium_pose_pose_orientation_z", "x_equilibrium_pose_pose_position_z"], "EmptyFieldRule", "auto");

% Import the data
data_eq = readtable("\\wsl.localhost\ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab4\matlab\data_eq.csv", opts);

%% Asignar a variables y rellenar NaN
tiempo = data_eq.x__time;
pos_x = data_eq.x_current_EE_pose_pose_position_x;
pos_y = data_eq.x_current_EE_pose_pose_position_y;
eq_x = data_eq.x_equilibrium_pose_pose_position_x;
eq_y = data_eq.x_equilibrium_pose_pose_position_y;

pos_x = fillmissing(pos_x, 'linear');
pos_y = fillmissing(pos_y, 'linear');
eq_x = fillmissing(eq_x, 'previous'); % Para referencias escalonadas, 'previous' suele ser mejor que 'linear'
eq_y = fillmissing(eq_y, 'previous');

% Normalizar tiempo
tiempo = tiempo - tiempo(1);

%% Clear temporary variables
clear opts data_eq