%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\wsl.localhost\ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab3\matlab\data_pd.csv
%
% Auto-generated by MATLAB on 13-Jun-2026 11:31:55

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x__time", "x_external_wrenches_force_x", "x_external_wrenches_force_y", "x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z", "x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_1_velocity", "x_joint_states_joint_2_position", "x_joint_states_joint_2_velocity"];
opts.SelectedVariableNames = ["x__time", "x_external_wrenches_force_x", "x_external_wrenches_force_y"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z", "x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_1_velocity", "x_joint_states_joint_2_position", "x_joint_states_joint_2_velocity"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["x_external_wrenches_force_z", "x_external_wrenches_torque_x", "x_external_wrenches_torque_y", "x_external_wrenches_torque_z", "x_joint_accelerations_data_0_", "x_joint_accelerations_data_1_", "x_joint_accelerations_layout_data_offset", "x_joint_states_header_stamp", "x_joint_states_joint_1_position", "x_joint_states_joint_1_velocity", "x_joint_states_joint_2_position", "x_joint_states_joint_2_velocity"], "EmptyFieldRule", "auto");

% Import the data
external_forces = readtable("\\wsl.localhost\ubuntu-22.04\home\ruben\ros\amp_rob_ws\src\uma_arm_control\archivos_informe\lab3\matlab\data_inc_g.csv", opts);

external_forces = table2array(external_forces);


%% Clear temporary variables
clear opts